import { getDb } from "../api/queries/connection";
import { categories, products, siteSettings, users } from "./schema";
import * as crypto from "node:crypto";
import { eq } from "drizzle-orm";

function hashPassword(password: string): string {
  const salt = crypto.randomBytes(16).toString("hex");
  const derivedKey = crypto.scryptSync(password, salt, 64).toString("hex");
  return `${salt}:${derivedKey}`;
}

async function seed() {
  const db = getDb();
  console.log("Seeding database...");

  // Seed categories
  const cats = await db.insert(categories).values([
    { name: "Smartphones", nameAr: "الهواتف الذكية", slug: "smartphones", icon: "Smartphone", sortOrder: 1, isActive: true },
    { name: "Laptops", nameAr: "أجهزة الكمبيوتر المحمولة", slug: "laptops", icon: "Laptop", sortOrder: 2, isActive: true },
    { name: "Tablets", nameAr: "الأجهزة اللوحية", slug: "tablets", icon: "Tablet", sortOrder: 3, isActive: true },
    { name: "Audio", nameAr: "الصوتيات", slug: "audio", icon: "Headphones", sortOrder: 4, isActive: true },
    { name: "Gaming", nameAr: "الألعاب", slug: "gaming", icon: "Gamepad2", sortOrder: 5, isActive: true },
    { name: "Accessories", nameAr: "الإكسسوارات", slug: "accessories", icon: "Watch", sortOrder: 6, isActive: true },
  ]).onConflictDoNothing();

  console.log("Categories seeded");

  // Seed products
  await db.insert(products).values([
    {
      name: "iPhone 15 Pro Max",
      nameAr: "آيفون 15 برو ماكس",
      slug: "iphone-15-pro-max",
      description: "The most powerful iPhone ever with A17 Pro chip, titanium design, and advanced camera system. Features a 6.7-inch Super Retina XDR display, 48MP main camera, and up to 29 hours of video playback.",
      shortDescription: "A17 Pro chip, titanium design, 48MP camera",
      categoryId: 1,
      brand: "Apple",
      sku: "IPH15PM-256",
      price: "64000.00",
      salePrice: "61000.00",
      image: "/products/iphone-15-pro-max.png",
      images: ["/products/iphone-15-pro-max.png"],
      stockQuantity: 50,
      status: "active",
      isFeatured: true,
      averageRating: "4.8",
      reviewCount: 256,
      weight: "221.00",
      metaTitle: "iPhone 15 Pro Max - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy iPhone 15 Pro Max in Egypt. Best price guaranteed.",
    },
    {
      name: "Samsung Galaxy S24 Ultra",
      nameAr: "سامسونج جالاكسي S24 الترا",
      slug: "samsung-galaxy-s24-ultra",
      description: "Galaxy AI is here. The S24 Ultra features a 200MP adaptive pixel camera, built-in S Pen, and the most powerful Snapdragon processor. 6.8-inch QHD+ display with 2600 nits peak brightness.",
      shortDescription: "Galaxy AI, 200MP camera, built-in S Pen",
      categoryId: 1,
      brand: "Samsung",
      sku: "SGS24U-256",
      price: "56000.00",
      salePrice: "52000.00",
      image: "/products/galaxy-s24-ultra.png",
      images: ["/products/galaxy-s24-ultra.png"],
      stockQuantity: 45,
      status: "active",
      isFeatured: true,
      averageRating: "4.7",
      reviewCount: 189,
      weight: "233.00",
      metaTitle: "Samsung Galaxy S24 Ultra - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Samsung Galaxy S24 Ultra in Egypt. Best price guaranteed.",
    },
    {
      name: "MacBook Pro M3",
      nameAr: "ماك بوك برو M3",
      slug: "macbook-pro-m3",
      description: "Supercharged by M3 chip, MacBook Pro is the most advanced Mac laptop ever. Features a stunning 16.2-inch Liquid Retina XDR display, up to 22 hours battery life, and pro-level performance.",
      shortDescription: "M3 chip, 16-inch Liquid Retina XDR, 22hr battery",
      categoryId: 2,
      brand: "Apple",
      sku: "MBP16-M3-512",
      price: "89000.00",
      salePrice: "85000.00",
      image: "/products/macbook-pro-m3.png",
      images: ["/products/macbook-pro-m3.png"],
      stockQuantity: 20,
      status: "active",
      isFeatured: true,
      averageRating: "4.9",
      reviewCount: 134,
      weight: "2140.00",
      metaTitle: "MacBook Pro M3 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy MacBook Pro M3 in Egypt. Best price guaranteed.",
    },
    {
      name: "Dell XPS 15",
      nameAr: "ديل XPS 15",
      slug: "dell-xps-15",
      description: "The Dell XPS 15 combines stunning design with powerful performance. Features a 15.6-inch InfinityEdge OLED display, 13th Gen Intel Core i7 processor, and NVIDIA GeForce RTX 4050 graphics.",
      shortDescription: "InfinityEdge OLED, Intel i7, RTX 4050",
      categoryId: 2,
      brand: "Dell",
      sku: "XPS15-9530",
      price: "95000.00",
      image: "/products/dell-xps-15.png",
      images: ["/products/dell-xps-15.png"],
      stockQuantity: 15,
      status: "active",
      isFeatured: false,
      averageRating: "4.5",
      reviewCount: 87,
      weight: "1860.00",
      metaTitle: "Dell XPS 15 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Dell XPS 15 in Egypt. Best price guaranteed.",
    },
    {
      name: "iPad Pro 12.9",
      nameAr: "آيباد برو 12.9",
      slug: "ipad-pro-12-9",
      description: "The ultimate iPad experience with M2 chip, 12.9-inch Liquid Retina XDR display, and support for Apple Pencil hover. Perfect for creative professionals and power users.",
      shortDescription: "M2 chip, 12.9-inch XDR display, Apple Pencil hover",
      categoryId: 3,
      brand: "Apple",
      sku: "IPADPRO129-256",
      price: "62000.00",
      salePrice: "59000.00",
      image: "/products/ipad-pro.png",
      images: ["/products/ipad-pro.png"],
      stockQuantity: 30,
      status: "active",
      isFeatured: true,
      averageRating: "4.8",
      reviewCount: 112,
      weight: "682.00",
      metaTitle: "iPad Pro 12.9 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy iPad Pro 12.9 in Egypt. Best price guaranteed.",
    },
    {
      name: "Samsung Galaxy Tab S9",
      nameAr: "سامسونج جالاكسي تاب S9",
      slug: "samsung-galaxy-tab-s9",
      description: "The Galaxy Tab S9 features a stunning 11-inch Dynamic AMOLED 2X display, Snapdragon 8 Gen 2 processor, and IP68 water resistance. Includes S Pen for ultimate productivity.",
      shortDescription: "11-inch AMOLED 2X, Snapdragon 8 Gen 2, IP68",
      categoryId: 3,
      brand: "Samsung",
      sku: "TAB-S9-128",
      price: "44000.00",
      image: "/products/galaxy-tab-s9.png",
      images: ["/products/galaxy-tab-s9.png"],
      stockQuantity: 25,
      status: "active",
      isFeatured: false,
      averageRating: "4.6",
      reviewCount: 76,
      weight: "498.00",
      metaTitle: "Samsung Galaxy Tab S9 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Samsung Galaxy Tab S9 in Egypt. Best price guaranteed.",
    },
    {
      name: "AirPods Pro 2",
      nameAr: "آيربودز برو 2",
      slug: "airpods-pro-2",
      description: "AirPods Pro 2 with H2 chip deliver up to 2x more Active Noise Cancellation. Adaptive Audio blends Active Noise Cancellation and Transparency mode. Personalized Spatial Audio with dynamic head tracking.",
      shortDescription: "H2 chip, 2x ANC, Adaptive Audio",
      categoryId: 4,
      brand: "Apple",
      sku: "APP2-USB-C",
      price: "12500.00",
      salePrice: "11200.00",
      image: "/products/airpods-pro-2.png",
      images: ["/products/airpods-pro-2.png"],
      stockQuantity: 100,
      status: "active",
      isFeatured: true,
      averageRating: "4.7",
      reviewCount: 342,
      weight: "50.00",
      metaTitle: "AirPods Pro 2 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy AirPods Pro 2 in Egypt. Best price guaranteed.",
    },
    {
      name: "Sony WH-1000XM5",
      nameAr: "سوني WH-1000XM5",
      slug: "sony-wh-1000xm5",
      description: "Industry-leading noise cancellation with two processors controlling eight microphones. Auto NC Optimizer for personalized noise canceling. Crystal clear hands-free calling and premium sound quality.",
      shortDescription: "Industry-leading ANC, 30hr battery, crystal clear calls",
      categoryId: 4,
      brand: "Sony",
      sku: "WH1000XM5-BLK",
      price: "19500.00",
      salePrice: "17900.00",
      image: "/products/sony-wh1000xm5.png",
      images: ["/products/sony-wh1000xm5.png"],
      stockQuantity: 40,
      status: "active",
      isFeatured: false,
      averageRating: "4.6",
      reviewCount: 198,
      weight: "250.00",
      metaTitle: "Sony WH-1000XM5 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Sony WH-1000XM5 in Egypt. Best price guaranteed.",
    },
    {
      name: "PlayStation 5",
      nameAr: "بلاي ستيشن 5",
      slug: "playstation-5",
      description: "Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio. Ray tracing brings new levels of realism.",
      shortDescription: "Ultra-high speed SSD, haptic feedback, ray tracing",
      categoryId: 5,
      brand: "Sony",
      sku: "PS5-STD",
      price: "28000.00",
      salePrice: "25500.00",
      image: "/products/playstation-5.png",
      images: ["/products/playstation-5.png"],
      stockQuantity: 35,
      status: "active",
      isFeatured: true,
      averageRating: "4.9",
      reviewCount: 567,
      weight: "4460.00",
      metaTitle: "PlayStation 5 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy PlayStation 5 in Egypt. Best price guaranteed.",
    },
    {
      name: "Xbox Series X",
      nameAr: "إكس بوكس سيريز إكس",
      slug: "xbox-series-x",
      description: "The most powerful Xbox ever. 12 teraflops of processing power, 1TB custom SSD, and 4K gaming at up to 120 FPS. Quick Resume lets you switch between games instantly.",
      shortDescription: "12 TFLOPS, 1TB SSD, 4K@120FPS, Quick Resume",
      categoryId: 5,
      brand: "Microsoft",
      sku: "XSX-1TB",
      price: "29000.00",
      image: "/products/xbox-series-x.png",
      images: ["/products/xbox-series-x.png"],
      stockQuantity: 30,
      status: "active",
      isFeatured: false,
      averageRating: "4.8",
      reviewCount: 423,
      weight: "4450.00",
      metaTitle: "Xbox Series X - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Xbox Series X in Egypt. Best price guaranteed.",
    },
    {
      name: "Apple Watch Ultra 2",
      nameAr: "آبل واتش ألترا 2",
      slug: "apple-watch-ultra-2",
      description: "The most rugged and capable Apple Watch. Features a 49mm aerospace-grade titanium case, precision dual-frequency GPS, and up to 36 hours of battery life. Water resistant to 100 meters.",
      shortDescription: "49mm titanium, dual-frequency GPS, 36hr battery",
      categoryId: 6,
      brand: "Apple",
      sku: "AWU2-49MM",
      price: "42000.00",
      salePrice: "39500.00",
      image: "/products/apple-watch-ultra-2.png",
      images: ["/products/apple-watch-ultra-2.png"],
      stockQuantity: 20,
      status: "active",
      isFeatured: true,
      averageRating: "4.8",
      reviewCount: 156,
      weight: "61.00",
      metaTitle: "Apple Watch Ultra 2 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Apple Watch Ultra 2 in Egypt. Best price guaranteed.",
    },
    {
      name: "Anker PowerCore 20000",
      nameAr: "أنكر باور كور 20000",
      slug: "anker-powercore-20000",
      description: "High-capacity portable charger with 20000mAh capacity. PowerIQ and VoltageBoost deliver the fastest possible charge. Dual USB ports allow simultaneous charging of two devices.",
      shortDescription: "20000mAh, PowerIQ, dual USB ports",
      categoryId: 6,
      brand: "Anker",
      sku: "ANKER-PC20K",
      price: "2500.00",
      image: "/products/anker-powercore.png",
      images: ["/products/anker-powercore.png"],
      stockQuantity: 200,
      status: "active",
      isFeatured: false,
      averageRating: "4.5",
      reviewCount: 892,
      weight: "350.00",
      metaDescription: "Buy Anker PowerCore 20000 in Egypt. Best price guaranteed.",
    },
    {
      name: "Samsung 65 Inch 4K Crystal UHD Smart TV",
      nameAr: "تلفزيون سامسونج 65 بوصة ذكي بدقة 4K",
      slug: "samsung-65-inch-4k-tv",
      description: "Experience crystal clear colors that are fine-tuned to deliver a naturally crisp and vivid picture. Smart TV powered by Tizen with multiple streaming apps.",
      shortDescription: "65 Inch, 4K UHD, Smart TV (Tizen)",
      categoryId: 1,
      brand: "Samsung",
      sku: "SAM-65TV-4K",
      price: "27000.00",
      salePrice: "24000.00",
      image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600",
      images: ["https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600"],
      stockQuantity: 15,
      status: "active",
      isFeatured: true,
      averageRating: "4.7",
      reviewCount: 312,
      weight: "20500.00",
      metaTitle: "Samsung 65 Inch 4K Smart TV",
      metaDescription: "Best deal on Samsung 65 Inch 4K TV in KSA",
    },
    {
      name: "De'Longhi Dedica Style Espresso Machine",
      nameAr: "ماكينة قهوة ديلونجي ديديكا اسبريسو",
      slug: "delonghi-dedica-espresso",
      description: "Brew your perfect espresso with the De'Longhi Dedica. 15 bar pressure creates an espresso with a rich aroma and a nut coloured cream on top. Adjustable milk frother.",
      shortDescription: "15 bar pressure, Adjustable milk frother, Slim design",
      categoryId: 6,
      brand: "De'Longhi",
      sku: "DEL-DEDICA-EC685",
      price: "10500.00",
      salePrice: "8900.00",
      image: "https://images.unsplash.com/photo-1585200236024-e1293fb8e2db?w=600",
      images: ["https://images.unsplash.com/photo-1585200236024-e1293fb8e2db?w=600"],
      stockQuantity: 25,
      status: "active",
      isFeatured: true,
      averageRating: "4.8",
      reviewCount: 845,
      weight: "4200.00",
      metaTitle: "DeLonghi Dedica Espresso Machine",
      metaDescription: "Buy DeLonghi Dedica Coffee Machine. Fast Delivery.",
    },
    {
      name: "Philips Essential Airfryer XL",
      nameAr: "قلاية فيليبس الهوائية إسينشال XL",
      slug: "philips-airfryer-xl",
      description: "Great tasting fries with up to 90% less fat! Thanks to Rapid Air technology. 1.2Kg capacity, perfect for families. Touch screen with 7 presets.",
      shortDescription: "1.2Kg Capacity, Rapid Air tech, 7 Presets",
      categoryId: 6,
      brand: "Philips",
      sku: "PHI-AIR-XL",
      price: "7500.00",
      salePrice: "6200.00",
      image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600",
      images: ["https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600"],
      stockQuantity: 40,
      status: "active",
      isFeatured: false,
      averageRating: "4.6",
      reviewCount: 1250,
      weight: "5500.00",
      metaTitle: "Philips Essential Airfryer XL",
      metaDescription: "Healthy cooking with Philips Airfryer XL.",
    },
    {
      name: "Sony ZV-E10 Mirrorless Vlog Camera",
      nameAr: "كاميرا سوني ZV-E10 فلوج بعدسات قابلة للتبديل",
      slug: "sony-zv-e10-vlog",
      description: "Designed for creative vloggers. Features a large APS-C sensor, Directional 3-Capsule Mic, and features designed for creators like Product Showcase Setting.",
      shortDescription: "APS-C Sensor, 4K Video, Perfect for Vlogging",
      categoryId: 4,
      brand: "Sony",
      sku: "SONY-ZVE10",
      price: "36000.00",
      image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600",
      images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600"],
      stockQuantity: 12,
      status: "active",
      isFeatured: true,
      averageRating: "4.9",
      reviewCount: 210,
      weight: "343.00",
      metaTitle: "Sony ZV-E10 Camera",
      metaDescription: "Best vlogging camera Sony ZV-E10.",
    },
    {
      name: "Google Pixel 8 Pro",
      nameAr: "جوجل بيكسل 8 برو",
      slug: "google-pixel-8-pro",
      description: "Google's best pro camera yet. Engineered by Google, it's custom-designed with the Google Tensor G3 chip and features advanced AI capabilities.",
      shortDescription: "Tensor G3, 50MP Camera, Advanced AI",
      categoryId: 1,
      brand: "Google",
      sku: "GOOG-P8P-256",
      price: "48000.00",
      salePrice: "44500.00",
      image: "https://images.unsplash.com/photo-1696446700622-c82ee33df6af?w=600",
      images: ["https://images.unsplash.com/photo-1696446700622-c82ee33df6af?w=600"],
      stockQuantity: 20,
      status: "active",
      isFeatured: false,
      averageRating: "4.7",
      reviewCount: 450,
      weight: "213.00",
      metaTitle: "Google Pixel 8 Pro",
      metaDescription: "Buy Google Pixel 8 Pro with AI features.",
    },
    {
      name: "Asus ROG Zephyrus G14",
      nameAr: "لابتوب اسوس روج زيفيروس G14",
      slug: "asus-rog-zephyrus-g14",
      description: "Powerful 14-inch gaming laptop featuring AMD Ryzen 9 and NVIDIA GeForce RTX 4060. AniMe Matrix LED display on the lid.",
      shortDescription: "Ryzen 9, RTX 4060, 14-inch 165Hz",
      categoryId: 2,
      brand: "Asus",
      sku: "ASUS-ROG-G14",
      price: "88000.00",
      salePrice: null,
      image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600",
      images: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600"],
      stockQuantity: 10,
      status: "active",
      isFeatured: true,
      averageRating: "4.8",
      reviewCount: 320,
      weight: "1650.00",
      metaTitle: "Asus ROG Zephyrus G14 Gaming Laptop",
      metaDescription: "Best 14-inch gaming laptop Asus ROG G14.",
    },
    {
      name: "Nintendo Switch OLED",
      nameAr: "نينتندو سويتش اوليد",
      slug: "nintendo-switch-oled",
      description: "Play at home or on the go with a vibrant 7-inch OLED screen. Features a wide adjustable stand, a dock with a wired LAN port, and 64 GB of internal storage.",
      shortDescription: "7-inch OLED, 64GB storage, Enhanced Audio",
      categoryId: 5,
      brand: "Nintendo",
      sku: "NIN-SW-OLED",
      price: "18500.00",
      salePrice: "16900.00",
      image: "https://images.unsplash.com/photo-1605901309584-818e25960b8f?w=600",
      images: ["https://images.unsplash.com/photo-1605901309584-818e25960b8f?w=600"],
      stockQuantity: 50,
      status: "active",
      isFeatured: false,
      averageRating: "4.9",
      reviewCount: 1800,
      weight: "420.00",
      metaTitle: "Nintendo Switch OLED Model",
      metaDescription: "Buy Nintendo Switch OLED at best price.",
    },
    {
      name: "Garmin Fenix 7 Sapphire Solar",
      nameAr: "ساعة جارمن فينيكس 7 ياقوت تعمل بالطاقة الشمسية",
      slug: "garmin-fenix-7",
      description: "Ultimate multisport GPS watch with solar charging. Scratch-resistant Power Sapphire lens, built-in sports apps, and advanced training features.",
      shortDescription: "Solar Charging, Sapphire Lens, GPS",
      categoryId: 6,
      brand: "Garmin",
      sku: "GAR-FENIX-7",
      price: "47000.00",
      salePrice: "43000.00",
      image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600",
      images: ["https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600"],
      stockQuantity: 15,
      status: "active",
      isFeatured: true,
      averageRating: "4.8",
      reviewCount: 650,
      weight: "73.00",
      metaTitle: "Garmin Fenix 7 Sapphire Solar",
      metaDescription: "Buy Garmin Fenix 7 smartwatch for fitness and outdoors.",
    }
  ]).onConflictDoNothing();

  console.log("Products seeded");

  // Seed default site settings
  await db.insert(siteSettings).values([
    { key: "siteName", value: "AL-YOUSEF ELECTRONICS" },
    { key: "contactLinks", value: { whatsapp: "", website: "", snapchat: "", twitter: "", telegram: "" } },
    { key: "theme", value: { primaryColor: "#1A2A44", accentColor: "#D4AF37", highlightColor: "#00D4FF" } },
    { key: "shipping", value: { freeThreshold: 500, defaultRate: 35 } },
    { key: "tax", value: { rate: 15, inclusive: false } },
  ]).onConflictDoNothing();

  console.log("Site settings seeded");

  // Seed Admin User
  const adminEmail = "admin@alyousef.com";
  const existingAdmin = await db.select().from(users).where(eq(users.email, adminEmail)).limit(1);
  if (existingAdmin.length === 0) {
    await db.insert(users).values({
      unionId: "local_admin",
      name: "Admin User",
      email: adminEmail,
      passwordHash: hashPassword("admin123"),
      role: "admin",
    }).onConflictDoNothing();
    console.log("Admin user seeded");
  }

  console.log("Seed complete!");
}

seed().catch(console.error);
