import { getDb } from "../api/queries/connection";
import { categories, products, siteSettings, users } from "./schema";
import * as crypto from "node:crypto";
import { eq } from "drizzle-orm";

function hashPassword(password: string): string {
  const salt = crypto.randomBytes(16).toString("hex");
  const derivedKey = crypto.scryptSync(password, salt, 64).toString("hex");
  return `${salt}:${derivedKey}`;
}

async function seed() {
  const db = getDb();
  console.log("Seeding database...");

  // Seed categories
  const cats = await db.insert(categories).values([
    { name: "Smartphones", nameAr: "الهواتف الذكية", slug: "smartphones", icon: "Smartphone", sortOrder: 1, isActive: true },
    { name: "Laptops", nameAr: "أجهزة الكمبيوتر المحمولة", slug: "laptops", icon: "Laptop", sortOrder: 2, isActive: true },
    { name: "Tablets", nameAr: "الأجهزة اللوحية", slug: "tablets", icon: "Tablet", sortOrder: 3, isActive: true },
    { name: "Audio", nameAr: "الصوتيات", slug: "audio", icon: "Headphones", sortOrder: 4, isActive: true },
    { name: "Gaming", nameAr: "الألعاب", slug: "gaming", icon: "Gamepad2", sortOrder: 5, isActive: true },
    { name: "Accessories", nameAr: "الإكسسوارات", slug: "accessories", icon: "Watch", sortOrder: 6, isActive: true },
  ]);

  console.log("Categories seeded");

  // Seed products
  await db.insert(products).values([
    {
      name: "iPhone 15 Pro Max",
      nameAr: "آيفون 15 برو ماكس",
      slug: "iphone-15-pro-max",
      description: "The most powerful iPhone ever with A17 Pro chip, titanium design, and advanced camera system. Features a 6.7-inch Super Retina XDR display, 48MP main camera, and up to 29 hours of video playback.",
      shortDescription: "A17 Pro chip, titanium design, 48MP camera",
      categoryId: 1,
      brand: "Apple",
      sku: "IPH15PM-256",
      price: "4599.00",
      salePrice: "4299.00",
      image: "/products/iphone-15-pro-max.png",
      images: ["/products/iphone-15-pro-max.png"],
      stockQuantity: 50,
      status: "active",
      isFeatured: true,
      averageRating: "4.8",
      reviewCount: 256,
      weight: "221.00",
      metaTitle: "iPhone 15 Pro Max - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy iPhone 15 Pro Max in Saudi Arabia. Best price guaranteed.",
    },
    {
      name: "Samsung Galaxy S24 Ultra",
      nameAr: "سامسونج جالاكسي S24 الترا",
      slug: "samsung-galaxy-s24-ultra",
      description: "Galaxy AI is here. The S24 Ultra features a 200MP adaptive pixel camera, built-in S Pen, and the most powerful Snapdragon processor. 6.8-inch QHD+ display with 2600 nits peak brightness.",
      shortDescription: "Galaxy AI, 200MP camera, built-in S Pen",
      categoryId: 1,
      brand: "Samsung",
      sku: "SGS24U-256",
      price: "4299.00",
      salePrice: "3999.00",
      image: "/products/galaxy-s24-ultra.png",
      images: ["/products/galaxy-s24-ultra.png"],
      stockQuantity: 45,
      status: "active",
      isFeatured: true,
      averageRating: "4.7",
      reviewCount: 189,
      weight: "233.00",
      metaTitle: "Samsung Galaxy S24 Ultra - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Samsung Galaxy S24 Ultra in Saudi Arabia. Best price guaranteed.",
    },
    {
      name: "MacBook Pro M3",
      nameAr: "ماك بوك برو M3",
      slug: "macbook-pro-m3",
      description: "Supercharged by M3 chip, MacBook Pro is the most advanced Mac laptop ever. Features a stunning 16.2-inch Liquid Retina XDR display, up to 22 hours battery life, and pro-level performance.",
      shortDescription: "M3 chip, 16-inch Liquid Retina XDR, 22hr battery",
      categoryId: 2,
      brand: "Apple",
      sku: "MBP16-M3-512",
      price: "7999.00",
      salePrice: "7599.00",
      image: "/products/macbook-pro-m3.png",
      images: ["/products/macbook-pro-m3.png"],
      stockQuantity: 20,
      status: "active",
      isFeatured: true,
      averageRating: "4.9",
      reviewCount: 134,
      weight: "2140.00",
      metaTitle: "MacBook Pro M3 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy MacBook Pro M3 in Saudi Arabia. Best price guaranteed.",
    },
    {
      name: "Dell XPS 15",
      nameAr: "ديل XPS 15",
      slug: "dell-xps-15",
      description: "The Dell XPS 15 combines stunning design with powerful performance. Features a 15.6-inch InfinityEdge OLED display, 13th Gen Intel Core i7 processor, and NVIDIA GeForce RTX 4050 graphics.",
      shortDescription: "InfinityEdge OLED, Intel i7, RTX 4050",
      categoryId: 2,
      brand: "Dell",
      sku: "XPS15-9530",
      price: "6499.00",
      image: "/products/dell-xps-15.png",
      images: ["/products/dell-xps-15.png"],
      stockQuantity: 15,
      status: "active",
      isFeatured: false,
      averageRating: "4.5",
      reviewCount: 87,
      weight: "1860.00",
      metaTitle: "Dell XPS 15 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Dell XPS 15 in Saudi Arabia. Best price guaranteed.",
    },
    {
      name: "iPad Pro 12.9",
      nameAr: "آيباد برو 12.9",
      slug: "ipad-pro-12-9",
      description: "The ultimate iPad experience with M2 chip, 12.9-inch Liquid Retina XDR display, and support for Apple Pencil hover. Perfect for creative professionals and power users.",
      shortDescription: "M2 chip, 12.9-inch XDR display, Apple Pencil hover",
      categoryId: 3,
      brand: "Apple",
      sku: "IPADPRO129-256",
      price: "3899.00",
      salePrice: "3699.00",
      image: "/products/ipad-pro.png",
      images: ["/products/ipad-pro.png"],
      stockQuantity: 30,
      status: "active",
      isFeatured: true,
      averageRating: "4.8",
      reviewCount: 112,
      weight: "682.00",
      metaTitle: "iPad Pro 12.9 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy iPad Pro 12.9 in Saudi Arabia. Best price guaranteed.",
    },
    {
      name: "Samsung Galaxy Tab S9",
      nameAr: "سامسونج جالاكسي تاب S9",
      slug: "samsung-galaxy-tab-s9",
      description: "The Galaxy Tab S9 features a stunning 11-inch Dynamic AMOLED 2X display, Snapdragon 8 Gen 2 processor, and IP68 water resistance. Includes S Pen for ultimate productivity.",
      shortDescription: "11-inch AMOLED 2X, Snapdragon 8 Gen 2, IP68",
      categoryId: 3,
      brand: "Samsung",
      sku: "TAB-S9-128",
      price: "2799.00",
      image: "/products/galaxy-tab-s9.png",
      images: ["/products/galaxy-tab-s9.png"],
      stockQuantity: 25,
      status: "active",
      isFeatured: false,
      averageRating: "4.6",
      reviewCount: 76,
      weight: "498.00",
      metaTitle: "Samsung Galaxy Tab S9 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Samsung Galaxy Tab S9 in Saudi Arabia. Best price guaranteed.",
    },
    {
      name: "AirPods Pro 2",
      nameAr: "آيربودز برو 2",
      slug: "airpods-pro-2",
      description: "AirPods Pro 2 with H2 chip deliver up to 2x more Active Noise Cancellation. Adaptive Audio blends Active Noise Cancellation and Transparency mode. Personalized Spatial Audio with dynamic head tracking.",
      shortDescription: "H2 chip, 2x ANC, Adaptive Audio",
      categoryId: 4,
      brand: "Apple",
      sku: "APP2-USB-C",
      price: "999.00",
      salePrice: "899.00",
      image: "/products/airpods-pro-2.png",
      images: ["/products/airpods-pro-2.png"],
      stockQuantity: 100,
      status: "active",
      isFeatured: true,
      averageRating: "4.7",
      reviewCount: 342,
      weight: "50.00",
      metaTitle: "AirPods Pro 2 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy AirPods Pro 2 in Saudi Arabia. Best price guaranteed.",
    },
    {
      name: "Sony WH-1000XM5",
      nameAr: "سوني WH-1000XM5",
      slug: "sony-wh-1000xm5",
      description: "Industry-leading noise cancellation with two processors controlling eight microphones. Auto NC Optimizer for personalized noise canceling. Crystal clear hands-free calling and premium sound quality.",
      shortDescription: "Industry-leading ANC, 30hr battery, crystal clear calls",
      categoryId: 4,
      brand: "Sony",
      sku: "WH1000XM5-BLK",
      price: "1299.00",
      salePrice: "1199.00",
      image: "/products/sony-wh1000xm5.png",
      images: ["/products/sony-wh1000xm5.png"],
      stockQuantity: 40,
      status: "active",
      isFeatured: false,
      averageRating: "4.6",
      reviewCount: 198,
      weight: "250.00",
      metaTitle: "Sony WH-1000XM5 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Sony WH-1000XM5 in Saudi Arabia. Best price guaranteed.",
    },
    {
      name: "PlayStation 5",
      nameAr: "بلاي ستيشن 5",
      slug: "playstation-5",
      description: "Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio. Ray tracing brings new levels of realism.",
      shortDescription: "Ultra-high speed SSD, haptic feedback, ray tracing",
      categoryId: 5,
      brand: "Sony",
      sku: "PS5-STD",
      price: "2599.00",
      salePrice: "2399.00",
      image: "/products/playstation-5.png",
      images: ["/products/playstation-5.png"],
      stockQuantity: 35,
      status: "active",
      isFeatured: true,
      averageRating: "4.9",
      reviewCount: 567,
      weight: "4460.00",
      metaTitle: "PlayStation 5 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy PlayStation 5 in Saudi Arabia. Best price guaranteed.",
    },
    {
      name: "Xbox Series X",
      nameAr: "إكس بوكس سيريز إكس",
      slug: "xbox-series-x",
      description: "The most powerful Xbox ever. 12 teraflops of processing power, 1TB custom SSD, and 4K gaming at up to 120 FPS. Quick Resume lets you switch between games instantly.",
      shortDescription: "12 TFLOPS, 1TB SSD, 4K@120FPS, Quick Resume",
      categoryId: 5,
      brand: "Microsoft",
      sku: "XSX-1TB",
      price: "2399.00",
      image: "/products/xbox-series-x.png",
      images: ["/products/xbox-series-x.png"],
      stockQuantity: 30,
      status: "active",
      isFeatured: false,
      averageRating: "4.8",
      reviewCount: 423,
      weight: "4450.00",
      metaTitle: "Xbox Series X - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Xbox Series X in Saudi Arabia. Best price guaranteed.",
    },
    {
      name: "Apple Watch Ultra 2",
      nameAr: "آبل واتش ألترا 2",
      slug: "apple-watch-ultra-2",
      description: "The most rugged and capable Apple Watch. Features a 49mm aerospace-grade titanium case, precision dual-frequency GPS, and up to 36 hours of battery life. Water resistant to 100 meters.",
      shortDescription: "49mm titanium, dual-frequency GPS, 36hr battery",
      categoryId: 6,
      brand: "Apple",
      sku: "AWU2-49MM",
      price: "2899.00",
      salePrice: "2699.00",
      image: "/products/apple-watch-ultra-2.png",
      images: ["/products/apple-watch-ultra-2.png"],
      stockQuantity: 20,
      status: "active",
      isFeatured: true,
      averageRating: "4.8",
      reviewCount: 156,
      weight: "61.00",
      metaTitle: "Apple Watch Ultra 2 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Apple Watch Ultra 2 in Saudi Arabia. Best price guaranteed.",
    },
    {
      name: "Anker PowerCore 20000",
      nameAr: "أنكر باور كور 20000",
      slug: "anker-powercore-20000",
      description: "High-capacity portable charger with 20000mAh capacity. PowerIQ and VoltageBoost deliver the fastest possible charge. Dual USB ports allow simultaneous charging of two devices.",
      shortDescription: "20000mAh, PowerIQ, dual USB ports",
      categoryId: 6,
      brand: "Anker",
      sku: "ANKER-PC20K",
      price: "249.00",
      image: "/products/anker-powercore.png",
      images: ["/products/anker-powercore.png"],
      stockQuantity: 200,
      status: "active",
      isFeatured: false,
      averageRating: "4.5",
      reviewCount: 892,
      weight: "350.00",
      metaTitle: "Anker PowerCore 20000 - AL-YOUSEF ELECTRONICS",
      metaDescription: "Buy Anker PowerCore 20000 in Saudi Arabia. Best price guaranteed.",
    },
  ]);

  console.log("Products seeded");

  // Seed default site settings
  await db.insert(siteSettings).values([
    { key: "siteName", value: "AL-YOUSEF ELECTRONICS" },
    { key: "contactLinks", value: { whatsapp: "", website: "", snapchat: "", twitter: "", telegram: "" } },
    { key: "theme", value: { primaryColor: "#1A2A44", accentColor: "#D4AF37", highlightColor: "#00D4FF" } },
    { key: "shipping", value: { freeThreshold: 500, defaultRate: 35 } },
    { key: "tax", value: { rate: 15, inclusive: false } },
  ]);

  console.log("Site settings seeded");

  // Seed Admin User
  const adminEmail = "admin@alyousef.com";
  const existingAdmin = await db.select().from(users).where(eq(users.email, adminEmail)).limit(1);
  if (existingAdmin.length === 0) {
    await db.insert(users).values({
      unionId: "local_admin",
      name: "Admin User",
      email: adminEmail,
      passwordHash: hashPassword("admin123"),
      role: "admin",
    });
    console.log("Admin user seeded");
  }

  console.log("Seed complete!");
}

seed().catch(console.error);
