export type EgyptGovernorate = {
  value: string;
  en: string;
  ar: string;
};

export type EgyptCenter = {
  value: string;
  en: string;
  ar: string;
};

export const egyptGovernorates: EgyptGovernorate[] = [
  { value: "Cairo", en: "Cairo", ar: "القاهرة" },
  { value: "Giza", en: "Giza", ar: "الجيزة" },
  { value: "Alexandria", en: "Alexandria", ar: "الإسكندرية" },
  { value: "Dakahlia", en: "Dakahlia", ar: "الدقهلية" },
  { value: "Red Sea", en: "Red Sea", ar: "البحر الأحمر" },
  { value: "Beheira", en: "Beheira", ar: "البحيرة" },
  { value: "Fayoum", en: "Fayoum", ar: "الفيوم" },
  { value: "Gharbia", en: "Gharbia", ar: "الغربية" },
  { value: "Ismailia", en: "Ismailia", ar: "الإسماعيلية" },
  { value: "Menofia", en: "Menofia", ar: "المنوفية" },
  { value: "Minya", en: "Minya", ar: "المنيا" },
  { value: "Qaliubiya", en: "Qaliubiya", ar: "القليوبية" },
  { value: "New Valley", en: "New Valley", ar: "الوادي الجديد" },
  { value: "Suez", en: "Suez", ar: "السويس" },
  { value: "Aswan", en: "Aswan", ar: "أسوان" },
  { value: "Assiut", en: "Assiut", ar: "أسيوط" },
  { value: "Beni Suef", en: "Beni Suef", ar: "بني سويف" },
  { value: "Port Said", en: "Port Said", ar: "بورسعيد" },
  { value: "Damietta", en: "Damietta", ar: "دمياط" },
  { value: "Sharkia", en: "Sharkia", ar: "الشرقية" },
  { value: "South Sinai", en: "South Sinai", ar: "جنوب سيناء" },
  { value: "Kafr El Sheikh", en: "Kafr El Sheikh", ar: "كفر الشيخ" },
  { value: "Matrouh", en: "Matrouh", ar: "مطروح" },
  { value: "Luxor", en: "Luxor", ar: "الأقصر" },
  { value: "Qena", en: "Qena", ar: "قنا" },
  { value: "North Sinai", en: "North Sinai", ar: "شمال سيناء" },
  { value: "Sohag", en: "Sohag", ar: "سوهاج" },
];

export const egyptGovernorateCenters: Record<string, EgyptCenter[]> = {
  Cairo: [
    { value: "Nasr City", en: "Nasr City", ar: "مدينة نصر" },
    { value: "Heliopolis", en: "Heliopolis", ar: "مصر الجديدة" },
    { value: "Maadi", en: "Maadi", ar: "المعادي" },
    { value: "New Cairo", en: "New Cairo", ar: "القاهرة الجديدة" },
    { value: "Shorouk", en: "Shorouk", ar: "الشروق" },
    { value: "Badr", en: "Badr", ar: "بدر" },
    { value: "Mokattam", en: "Mokattam", ar: "المقطم" },
    { value: "Downtown Cairo", en: "Downtown Cairo", ar: "وسط البلد" },
    { value: "Zamalek", en: "Zamalek", ar: "الزمالك" },
    { value: "Shubra", en: "Shubra", ar: "شبرا" },
    { value: "Helwan", en: "Helwan", ar: "حلوان" },
    { value: "15 May", en: "15 May", ar: "15 مايو" },
  ],
  Giza: [
    { value: "Giza", en: "Giza", ar: "الجيزة" },
    { value: "6th of October", en: "6th of October", ar: "6 أكتوبر" },
    { value: "Sheikh Zayed", en: "Sheikh Zayed", ar: "الشيخ زايد" },
    { value: "Dokki", en: "Dokki", ar: "الدقي" },
    { value: "Mohandessin", en: "Mohandessin", ar: "المهندسين" },
    { value: "Imbaba", en: "Imbaba", ar: "إمبابة" },
    { value: "Kerdasa", en: "Kerdasa", ar: "كرداسة" },
    { value: "Abu Nomros", en: "Abu Nomros", ar: "أبو النمرس" },
    { value: "Hawamdeya", en: "Hawamdeya", ar: "الحوامدية" },
    { value: "Badrashein", en: "Badrashein", ar: "البدرشين" },
    { value: "Ayat", en: "Ayat", ar: "العياط" },
    { value: "Saff", en: "Saff", ar: "الصف" },
    { value: "Atfih", en: "Atfih", ar: "أطفيح" },
    { value: "Osim", en: "Osim", ar: "أوسيم" },
  ],
  Alexandria: [
    { value: "Montaza", en: "Montaza", ar: "المنتزه" },
    { value: "Raml", en: "Raml", ar: "الرمل" },
    { value: "Sidi Gaber", en: "Sidi Gaber", ar: "سيدي جابر" },
    { value: "Bab Sharqi", en: "Bab Sharqi", ar: "باب شرقي" },
    { value: "Moharam Bek", en: "Moharam Bek", ar: "محرم بك" },
    { value: "Mina El Basal", en: "Mina El Basal", ar: "مينا البصل" },
    { value: "Agami", en: "Agami", ar: "العجمي" },
    { value: "Amreya", en: "Amreya", ar: "العامرية" },
    { value: "Borg El Arab", en: "Borg El Arab", ar: "برج العرب" },
  ],
  Dakahlia: [
    { value: "Mansoura", en: "Mansoura", ar: "المنصورة" },
    { value: "Talkha", en: "Talkha", ar: "طلخا" },
    { value: "Mit Ghamr", en: "Mit Ghamr", ar: "ميت غمر" },
    { value: "Aga", en: "Aga", ar: "أجا" },
    { value: "Sinbillawin", en: "Sinbillawin", ar: "السنبلاوين" },
    { value: "Sherbin", en: "Sherbin", ar: "شربين" },
    { value: "Belqas", en: "Belqas", ar: "بلقاس" },
    { value: "Dekernes", en: "Dekernes", ar: "دكرنس" },
    { value: "Manzala", en: "Manzala", ar: "المنزلة" },
    { value: "Gamasa", en: "Gamasa", ar: "جمصة" },
    { value: "Nabaroh", en: "Nabaroh", ar: "نبروه" },
  ],
  "Red Sea": [
    { value: "Hurghada", en: "Hurghada", ar: "الغردقة" },
    { value: "Ras Gharib", en: "Ras Gharib", ar: "رأس غارب" },
    { value: "Safaga", en: "Safaga", ar: "سفاجا" },
    { value: "Quseir", en: "Quseir", ar: "القصير" },
    { value: "Marsa Alam", en: "Marsa Alam", ar: "مرسى علم" },
    { value: "Shalateen", en: "Shalateen", ar: "الشلاتين" },
    { value: "Halaib", en: "Halaib", ar: "حلايب" },
  ],
  Beheira: [
    { value: "Damanhur", en: "Damanhur", ar: "دمنهور" },
    { value: "Kafr El Dawwar", en: "Kafr El Dawwar", ar: "كفر الدوار" },
    { value: "Rashid", en: "Rashid", ar: "رشيد" },
    { value: "Edku", en: "Edku", ar: "إدكو" },
    { value: "Abu Hummus", en: "Abu Hummus", ar: "أبو حمص" },
    { value: "Hosh Essa", en: "Hosh Essa", ar: "حوش عيسى" },
    { value: "Delengat", en: "Delengat", ar: "الدلنجات" },
    { value: "Kom Hamada", en: "Kom Hamada", ar: "كوم حمادة" },
    { value: "Itay El Baroud", en: "Itay El Baroud", ar: "إيتاي البارود" },
    { value: "Wadi El Natrun", en: "Wadi El Natrun", ar: "وادي النطرون" },
    { value: "Badr Beheira", en: "Badr", ar: "بدر" },
    { value: "Nubaria", en: "Nubaria", ar: "النوبارية" },
  ],
  Fayoum: [
    { value: "Fayoum", en: "Fayoum", ar: "الفيوم" },
    { value: "Sinnuris", en: "Sinnuris", ar: "سنورس" },
    { value: "Tamiya", en: "Tamiya", ar: "طامية" },
    { value: "Ibshaway", en: "Ibshaway", ar: "إبشواي" },
    { value: "Youssef El Seddik", en: "Youssef El Seddik", ar: "يوسف الصديق" },
    { value: "Itsa", en: "Itsa", ar: "إطسا" },
  ],
  Gharbia: [
    { value: "Tanta", en: "Tanta", ar: "طنطا" },
    { value: "Mahalla El Kubra", en: "Mahalla El Kubra", ar: "المحلة الكبرى" },
    { value: "Kafr El Zayat", en: "Kafr El Zayat", ar: "كفر الزيات" },
    { value: "Zefta", en: "Zefta", ar: "زفتى" },
    { value: "Samanoud", en: "Samanoud", ar: "سمنود" },
    { value: "Qutour", en: "Qutour", ar: "قطور" },
    { value: "Basyoun", en: "Basyoun", ar: "بسيون" },
    { value: "Santa", en: "Santa", ar: "السنطة" },
  ],
  Ismailia: [
    { value: "Ismailia", en: "Ismailia", ar: "الإسماعيلية" },
    { value: "Fayed", en: "Fayed", ar: "فايد" },
    { value: "Qantara West", en: "Qantara West", ar: "القنطرة غرب" },
    { value: "Qantara East", en: "Qantara East", ar: "القنطرة شرق" },
    { value: "Tal El Kebir", en: "Tal El Kebir", ar: "التل الكبير" },
    { value: "Abu Suwir", en: "Abu Suwir", ar: "أبو صوير" },
    { value: "Qassasin", en: "Qassasin", ar: "القصاصين" },
  ],
  Menofia: [
    { value: "Shibin El Kom", en: "Shibin El Kom", ar: "شبين الكوم" },
    { value: "Menouf", en: "Menouf", ar: "منوف" },
    { value: "Ashmoun", en: "Ashmoun", ar: "أشمون" },
    { value: "Quesna", en: "Quesna", ar: "قويسنا" },
    { value: "Tala", en: "Tala", ar: "تلا" },
    { value: "Bagour", en: "Bagour", ar: "الباجور" },
    { value: "Berket El Saba", en: "Berket El Saba", ar: "بركة السبع" },
    { value: "Sadat City", en: "Sadat City", ar: "مدينة السادات" },
    { value: "Shohada", en: "Shohada", ar: "الشهداء" },
  ],
  Minya: [
    { value: "Minya", en: "Minya", ar: "المنيا" },
    { value: "New Minya", en: "New Minya", ar: "المنيا الجديدة" },
    { value: "Mallawi", en: "Mallawi", ar: "ملوي" },
    { value: "Samalut", en: "Samalut", ar: "سمالوط" },
    { value: "Beni Mazar", en: "Beni Mazar", ar: "بني مزار" },
    { value: "Maghagha", en: "Maghagha", ar: "مغاغة" },
    { value: "Matai", en: "Matai", ar: "مطاي" },
    { value: "Abu Qurqas", en: "Abu Qurqas", ar: "أبو قرقاص" },
    { value: "Deir Mawas", en: "Deir Mawas", ar: "دير مواس" },
    { value: "Adwa", en: "Adwa", ar: "العدوة" },
  ],
  Qaliubiya: [
    { value: "Banha", en: "Banha", ar: "بنها" },
    { value: "Shubra El Kheima", en: "Shubra El Kheima", ar: "شبرا الخيمة" },
    { value: "Qalyub", en: "Qalyub", ar: "قليوب" },
    { value: "Qanater El Khairiya", en: "Qanater El Khairiya", ar: "القناطر الخيرية" },
    { value: "Khanka", en: "Khanka", ar: "الخانكة" },
    { value: "Khosous", en: "Khosous", ar: "الخصوص" },
    { value: "Obour", en: "Obour", ar: "العبور" },
    { value: "Shibin El Qanater", en: "Shibin El Qanater", ar: "شبين القناطر" },
    { value: "Tukh", en: "Tukh", ar: "طوخ" },
    { value: "Kafr Shukr", en: "Kafr Shukr", ar: "كفر شكر" },
  ],
  "New Valley": [
    { value: "Kharga", en: "Kharga", ar: "الخارجة" },
    { value: "Dakhla", en: "Dakhla", ar: "الداخلة" },
    { value: "Farafra", en: "Farafra", ar: "الفرافرة" },
    { value: "Baris", en: "Baris", ar: "باريس" },
    { value: "Balat", en: "Balat", ar: "بلاط" },
  ],
  Suez: [
    { value: "Suez", en: "Suez", ar: "السويس" },
    { value: "Arbaeen", en: "Arbaeen", ar: "الأربعين" },
    { value: "Attaka", en: "Attaka", ar: "عتاقة" },
    { value: "Faisal Suez", en: "Faisal", ar: "فيصل" },
    { value: "Ganayen", en: "Ganayen", ar: "الجناين" },
  ],
  Aswan: [
    { value: "Aswan", en: "Aswan", ar: "أسوان" },
    { value: "Daraw", en: "Daraw", ar: "دراو" },
    { value: "Kom Ombo", en: "Kom Ombo", ar: "كوم أمبو" },
    { value: "Nasr El Nuba", en: "Nasr El Nuba", ar: "نصر النوبة" },
    { value: "Edfu", en: "Edfu", ar: "إدفو" },
    { value: "Abu Simbel", en: "Abu Simbel", ar: "أبو سمبل" },
  ],
  Assiut: [
    { value: "Assiut", en: "Assiut", ar: "أسيوط" },
    { value: "New Assiut", en: "New Assiut", ar: "أسيوط الجديدة" },
    { value: "Dayrout", en: "Dayrout", ar: "ديروط" },
    { value: "Qusiya", en: "Qusiya", ar: "القوصية" },
    { value: "Manfalut", en: "Manfalut", ar: "منفلوط" },
    { value: "Abnoub", en: "Abnoub", ar: "أبنوب" },
    { value: "Abu Tig", en: "Abu Tig", ar: "أبو تيج" },
    { value: "Ghanayem", en: "Ghanayem", ar: "الغنايم" },
    { value: "Sahel Selim", en: "Sahel Selim", ar: "ساحل سليم" },
    { value: "Badari", en: "Badari", ar: "البداري" },
    { value: "Sidfa", en: "Sidfa", ar: "صدفا" },
  ],
  "Beni Suef": [
    { value: "Beni Suef", en: "Beni Suef", ar: "بني سويف" },
    { value: "New Beni Suef", en: "New Beni Suef", ar: "بني سويف الجديدة" },
    { value: "Wasta", en: "Wasta", ar: "الواسطى" },
    { value: "Nasser", en: "Nasser", ar: "ناصر" },
    { value: "Ihnasiya", en: "Ihnasiya", ar: "إهناسيا" },
    { value: "Beba", en: "Beba", ar: "ببا" },
    { value: "Samasta", en: "Samasta", ar: "سمسطا" },
    { value: "Fashn", en: "Fashn", ar: "الفشن" },
  ],
  "Port Said": [
    { value: "Port Fouad", en: "Port Fouad", ar: "بورفؤاد" },
    { value: "El Sharq", en: "El Sharq", ar: "حي الشرق" },
    { value: "El Arab", en: "El Arab", ar: "حي العرب" },
    { value: "El Manakh", en: "El Manakh", ar: "المناخ" },
    { value: "El Dawahy", en: "El Dawahy", ar: "الضواحي" },
    { value: "El Zohour", en: "El Zohour", ar: "الزهور" },
    { value: "El Ganoub", en: "El Ganoub", ar: "الجنوب" },
  ],
  Damietta: [
    { value: "Damietta", en: "Damietta", ar: "دمياط" },
    { value: "New Damietta", en: "New Damietta", ar: "دمياط الجديدة" },
    { value: "Ras El Bar", en: "Ras El Bar", ar: "رأس البر" },
    { value: "Faraskur", en: "Faraskur", ar: "فارسكور" },
    { value: "Zarqa", en: "Zarqa", ar: "الزرقا" },
    { value: "Kafr Saad", en: "Kafr Saad", ar: "كفر سعد" },
    { value: "Kafr El Battikh", en: "Kafr El Battikh", ar: "كفر البطيخ" },
  ],
  Sharkia: [
    { value: "Zagazig", en: "Zagazig", ar: "الزقازيق" },
    { value: "10th of Ramadan", en: "10th of Ramadan", ar: "العاشر من رمضان" },
    { value: "Belbeis", en: "Belbeis", ar: "بلبيس" },
    { value: "Minya El Qamh", en: "Minya El Qamh", ar: "منيا القمح" },
    { value: "Abu Hammad", en: "Abu Hammad", ar: "أبو حماد" },
    { value: "Abu Kabir", en: "Abu Kabir", ar: "أبو كبير" },
    { value: "Faqous", en: "Faqous", ar: "فاقوس" },
    { value: "Hehya", en: "Hehya", ar: "ههيا" },
    { value: "Kafr Saqr", en: "Kafr Saqr", ar: "كفر صقر" },
    { value: "Awlad Saqr", en: "Awlad Saqr", ar: "أولاد صقر" },
    { value: "Mashtoul El Souk", en: "Mashtoul El Souk", ar: "مشتول السوق" },
    { value: "Diyarb Negm", en: "Diyarb Negm", ar: "ديرب نجم" },
    { value: "Ibrahimia", en: "Ibrahimia", ar: "الإبراهيمية" },
    { value: "Qareen", en: "Qareen", ar: "القرين" },
    { value: "Salhiya", en: "Salhiya", ar: "الصالحية الجديدة" },
  ],
  "South Sinai": [
    { value: "El Tor", en: "El Tor", ar: "الطور" },
    { value: "Sharm El Sheikh", en: "Sharm El Sheikh", ar: "شرم الشيخ" },
    { value: "Dahab", en: "Dahab", ar: "دهب" },
    { value: "Nuweiba", en: "Nuweiba", ar: "نويبع" },
    { value: "Taba", en: "Taba", ar: "طابا" },
    { value: "Ras Sedr", en: "Ras Sedr", ar: "رأس سدر" },
    { value: "Saint Catherine", en: "Saint Catherine", ar: "سانت كاترين" },
    { value: "Abu Zenima", en: "Abu Zenima", ar: "أبو زنيمة" },
    { value: "Abu Redis", en: "Abu Redis", ar: "أبو رديس" },
  ],
  "Kafr El Sheikh": [
    { value: "Kafr El Sheikh", en: "Kafr El Sheikh", ar: "كفر الشيخ" },
    { value: "Desouk", en: "Desouk", ar: "دسوق" },
    { value: "Fouh", en: "Fouh", ar: "فوه" },
    { value: "Metoubes", en: "Metoubes", ar: "مطوبس" },
    { value: "Biyala", en: "Biyala", ar: "بيلا" },
    { value: "Hamoul", en: "Hamoul", ar: "الحامول" },
    { value: "Baltim", en: "Baltim", ar: "بلطيم" },
    { value: "Riyadh", en: "Riyadh", ar: "الرياض" },
    { value: "Sidi Salem", en: "Sidi Salem", ar: "سيدي سالم" },
    { value: "Qallin", en: "Qallin", ar: "قلين" },
  ],
  Matrouh: [
    { value: "Marsa Matrouh", en: "Marsa Matrouh", ar: "مرسى مطروح" },
    { value: "Hammam", en: "Hammam", ar: "الحمام" },
    { value: "Alamein", en: "Alamein", ar: "العلمين" },
    { value: "Dabaa", en: "Dabaa", ar: "الضبعة" },
    { value: "Nagila", en: "Nagila", ar: "النجيلة" },
    { value: "Sidi Barrani", en: "Sidi Barrani", ar: "سيدي براني" },
    { value: "Salloum", en: "Salloum", ar: "السلوم" },
    { value: "Siwa", en: "Siwa", ar: "سيوة" },
  ],
  Luxor: [
    { value: "Luxor", en: "Luxor", ar: "الأقصر" },
    { value: "New Thebes", en: "New Thebes", ar: "طيبة الجديدة" },
    { value: "Bayadeya", en: "Bayadeya", ar: "البياضية" },
    { value: "Qurna", en: "Qurna", ar: "القرنة" },
    { value: "Armant", en: "Armant", ar: "أرمنت" },
    { value: "Esna", en: "Esna", ar: "إسنا" },
    { value: "Tod", en: "Tod", ar: "الطود" },
  ],
  Qena: [
    { value: "Qena", en: "Qena", ar: "قنا" },
    { value: "New Qena", en: "New Qena", ar: "قنا الجديدة" },
    { value: "Abu Tesht", en: "Abu Tesht", ar: "أبو تشت" },
    { value: "Farshout", en: "Farshout", ar: "فرشوط" },
    { value: "Nag Hammadi", en: "Nag Hammadi", ar: "نجع حمادي" },
    { value: "Dishna", en: "Dishna", ar: "دشنا" },
    { value: "Waqf", en: "Waqf", ar: "الوقف" },
    { value: "Qift", en: "Qift", ar: "قفط" },
    { value: "Qus", en: "Qus", ar: "قوص" },
    { value: "Naqada", en: "Naqada", ar: "نقادة" },
  ],
  "North Sinai": [
    { value: "Arish", en: "Arish", ar: "العريش" },
    { value: "Sheikh Zuweid", en: "Sheikh Zuweid", ar: "الشيخ زويد" },
    { value: "Rafah", en: "Rafah", ar: "رفح" },
    { value: "Bir El Abd", en: "Bir El Abd", ar: "بئر العبد" },
    { value: "Nakhl", en: "Nakhl", ar: "نخل" },
    { value: "Hasana", en: "Hasana", ar: "الحسنة" },
  ],
  Sohag: [
    { value: "Sohag", en: "Sohag", ar: "سوهاج" },
    { value: "New Sohag", en: "New Sohag", ar: "سوهاج الجديدة" },
    { value: "Akhmim", en: "Akhmim", ar: "أخميم" },
    { value: "Akhmim New City", en: "Akhmim New City", ar: "أخميم الجديدة" },
    { value: "Gerga", en: "Gerga", ar: "جرجا" },
    { value: "Dar El Salam", en: "Dar El Salam", ar: "دار السلام" },
    { value: "Tahta", en: "Tahta", ar: "طهطا" },
    { value: "Tima", en: "Tima", ar: "طما" },
    { value: "Maragha", en: "Maragha", ar: "المراغة" },
    { value: "Monshaah", en: "Monshaah", ar: "المنشأة" },
    { value: "Baliana", en: "Baliana", ar: "البلينا" },
    { value: "Juhayna", en: "Juhayna", ar: "جهينة" },
    { value: "Saqilta", en: "Saqilta", ar: "ساقلته" },
  ],
};

export function getGovernorateLabel(value: string | null | undefined, lang: string) {
  const governorate = egyptGovernorates.find((item) => item.value === value);
  if (!governorate) return value || "";
  return lang === "ar" ? governorate.ar : governorate.en;
}

export function getGovernorateCenters(governorate: string | null | undefined) {
  return governorate ? (egyptGovernorateCenters[governorate] ?? []) : [];
}
